title: Eric Xu Cui
logo: /Assets/EricPFP.jpg
description: Undergraduate @McGill University Majoring BS. Computer Science - Artificial Intelligence and Minoring Mathmatics
#show_downloads: true
theme: jekyll-theme-minimal
