title: Eric Xu Cui
logo: /Assets/EricPFP.jpg
description: Undergraduate @McGill University Majoring BS. Computer Science Honours and minoring Mathematics
#show_downloads: true
theme: jekyll-theme-minimal
