title: Eric Xu Cui
logo: /Assets/EricPFP.jpg
description: Majoring BS. Computer Science - Artificial Intelligence and Minor in Mathmatics @McGill University
#show_downloads: true
theme: jekyll-theme-minimal
